sudo: required
service:
  - docker

before_install:
  - docker build -t shijujohn1093/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shijujohn1093/react-test npm test

after_success:
  - docker build -t shijujohn1093/multi-client ./client
  - docker build -t shijujohn1093/multi-nginx ./nginx
  - docker build -t shijujohn1093/multi-server ./server
  - docker build -t shijujohn1093/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push shijujohn1093/multi-client
  - docker push shijujohn1093/multi-nginx
  - docker push shijujohn1093/multi-server
  - docker push shijujohn1093/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-south-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-south-1-287408872399
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

